services:
  backend:
    build: .
    container_name: agentic-backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://db:27017/
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: always
    depends_on:
      - db
    networks:
      - agentic-network

  db:
    image: mongo:latest
    restart: always
    container_name: agentic-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    networks:
      - agentic-network

networks:
  agentic-network:
    driver: bridge
