[project]
name = "aibots-research-agent"
version = "0.1.0"
description = "Agentic workflow for research"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.8",
    "uvicorn[standard]>=0.34.0",
]
